version: '3.7'

services:
  postgres:
    image: postgres
    container_name: realtime-chatapp
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nikenhpsr
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: chatapp
    volumes:
      - realtime-chatapp:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  realtime-chatapp:
